### ISSUE TITLE
SR-17-0000298 FD Image Trend reporting process

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [CityofMadisonAccela/DevTeam2#1]
FD Image Trend reporting process - 

Fire will be receiving a file from Image Trend that they would like to use for reporting. This file will be received by Chris and used to populate a database at Itnetapp\sql2014 named Elite_DWDaneCounty. To only allow Chris to report on City of Madison Fire Incidents, we will create views that filter out all records but Madison Fire and create a read only user that Chris will use for reporting.

We will know when this project is done when we go through 3 months of the process occurring and Chris is able to produce a report consistently in that time period.

**Comment by rsjachrani-com** [comment]
Created views, asked Tim to create read only user to use. Tim asked Chris about a more recent bak from from Image Trend
