### ISSUE TITLE
Java GIS Map in dev - Undefined error with Planning and Tax Parcels

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [CityofMadisonAccela/DevTeam2#2]

**Comment by rsjachrani-com** [comment]
When setting the primary field to parcel in accela gis admin we are seeing the undefined error through Accela GIS.

We believe it has something to do with the index setup through the arcgis mxd configuration. Paul is going to bug Aaron about this

![image](https://user-images.githubusercontent.com/13784495/28385808-07d16dde-6c8f-11e7-8e4a-259667956c8c.png)
